## Least squares approximate solution in Julia

The Math:

- $\hat x$ minimizes $\lVert Ax-b \rVert ^2$, where $A$ has independent columns
- $\hat x = (A^T A)^{-1} A^T b = A^\dagger b = R^{-1}Q^T b$ 

In Julia:

In [1]:
A = rand(5, 3)
b = rand(5)
xhat = inv(A'*A) * A'*b

3-element Array{Float64,1}:
  0.547062
 -1.06301 
  2.0767  

In [2]:
xhat = pinv(A) * b

3-element Array{Float64,1}:
  0.547062
 -1.06301 
  2.0767  

In [3]:
Q, R = qr(A); xhat = inv(R) * Q'*b

3-element Array{Float64,1}:
  0.547062
 -1.06301 
  2.0767  

In [4]:
xhat = A\b

3-element Array{Float64,1}:
  0.547062
 -1.06301 
  2.0767  

## Linear regression

- $N$ columns of $X$ are feature $n$-vectors
- $N$-vector $y$ gives associated outcomes
- regression model: find $n$-vector $\beta$, scalar $v$ that minimize

$$
\left\lVert X^T \beta + v - y \right\rVert ^2
$$
  
- express objective as

$$
\left\lVert \left[1 X^T \right] \left[ \begin{array}{c}
v \\
\beta
\end{array} \right]
- y
\right\rVert ^2
$$

- in Julia:

        beta_tilde = [ ones(N,1) X’ ] \ y;
        v = beta_tilde[1];  beta = beta_tilde[2:end];

## Multi-objective least squares

the math for two objectives:

- $\hat x$ minimizes $\lambda_1 \lVert A_1 x - b_1 \rVert^2 + \lambda_2 \lVert A_2 x - b_2 \rVert ^2$
- $\lambda_1, \lambda_2 > 0$ are relative weights, tradeoff objectives
- solve by stacking:

$$
\hat x = \left[ \begin{array}{c}
\sqrt{\lambda_1} A_1 \\
\sqrt{\lambda_2} A_2
\end{array}\right] ^\dagger
\left[ \begin{array}{c}
\sqrt{\lambda_1} b_1 \\
\sqrt{\lambda_2} b_2
\end{array}\right]
$$

or

$$
\hat x = \left( \lambda_1 A_1^T A_1 + \lambda_2 A_2^T A_2 \right)^{-1} + \left( \lambda_1 A_1^T b_1 + \lambda_2 A_2^T b_2 \right)
$$

in Julia:

    sl1 = sqrt(lambda1); sl2 = sqrt(lambda2);
    x_hat = [sl1 * A1; sl2*A2] \ [sl1*b1; sl2*b2]

## Equality constrained least squares

the math

- $\hat x$ minimizes $\left\lVert Ax-b \right\rVert^2$ subject to $Cx = d$
- $A$ is $m \times n$, $C$ is $p \times n$
- find $\hat x$ by solving $(n+p) \times (n+p)$ KKT system


$$
\left[ \begin{array}{cc}
2A^T A & C^T \\
C      & 0 \\
\end{array} \right]
 \left[ \begin{array}{c}
\hat x \\
z
\end{array} \right] = \left[ \begin{array}{c}
2A^T b \\
d \end{array} \right]
$$

In Julia:

    kkt_sol = [2*A'*A C'; C zeros(p,p)] \ [2*A'*b; d]
    x_hat = kkt_sol[1:n]

## Least norm problem

The math:

- $\hat x$ minimizes $\lVert x \rVert^2$ subject to $Cx=d$
- can solve by KKT system, or $\hat x = C^T(C C^T)^{-1} d = C^\dagger d$

In Julia:

    x_hat = C \ d