## Vectors

Vectors are represented by arrays

In [1]:
x = [8, -4, 3.5]

3-element Array{Float64,1}:
  8.0
 -4.0
  3.5

In [2]:
x'

1×3 Array{Float64,2}:
 8.0  -4.0  3.5

In [3]:
length(x)

3

## Ranges

Ranges are lazy

In [4]:
1:10

1:10

In [5]:
collect(1:10)

10-element Array{Int64,1}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [6]:
collect(1:0.5:3)

5-element Array{Float64,1}:
 1.0
 1.5
 2.0
 2.5
 3.0

## Indexing and slicing

indexes run from $1$ to $n$

In [7]:
x = 0:0.1:10
x[1], x[2]

(0.0,0.1)

In [8]:
x[3] = 6

LoadError: indexed assignment not defined for FloatRange{Float64}

In [9]:
x = collect(0:0.1:10);

In [10]:
x[3] = 6

6

In [11]:
x[1:5]

5-element Array{Float64,1}:
 0.0
 0.1
 6.0
 0.3
 0.4

In [12]:
x[end]

10.0

In [13]:
x[1:2:end]

51-element Array{Float64,1}:
  0.0
  6.0
  0.4
  0.6
  0.8
  1.0
  1.2
  1.4
  1.6
  1.8
  2.0
  2.2
  2.4
  ⋮  
  7.8
  8.0
  8.2
  8.4
  8.6
  8.8
  9.0
  9.2
  9.4
  9.6
  9.8
 10.0

## Block vectors

In [14]:
a = 1:5
b = 10:15
c = 6
x = [a ; -10 ; b; c]

13-element Array{Int64,1}:
   1
   2
   3
   4
   5
 -10
  10
  11
  12
  13
  14
  15
   6

## basic functions for arrays

In [15]:
sum(x)

86

In [16]:
mean(x)

6.615384615384615

In [17]:
zeros(3)

3-element Array{Float64,1}:
 0.0
 0.0
 0.0

In [18]:
ones(3)

3-element Array{Float64,1}:
 1.0
 1.0
 1.0

## Creating unit vectors

In [19]:
e_3 = zeros(10); e_3[3] = 1;

## List of vectors

to form a list with vectors `a`, `b` and `c`:

In [20]:
vector_list = [a,b,c]

3-element Array{Any,1}:
  1:5  
  10:15
 6     

In [21]:
vector_list[2]

10:15

In [22]:
vector_list[2][2]

11

## Vector addition and subtraction

Vector addition uses `+`, for example 

$$
\left[
\begin{array}{c}
1 \\
2 \\
3
\end{array}
\right]
+
\left[
\begin{array}{c}
4 \\
5 \\
6
\end{array}
\right]
$$

is written as follows

In [23]:
[1, 2, 3] + [4, 5, 6]

3-element Array{Int64,1}:
 5
 7
 9

In [24]:
[1, 2, 3] + 10

3-element Array{Int64,1}:
 11
 12
 13

## Scalar-vector multiplication

In [25]:
-2 * [1, 9, 6]

3-element Array{Int64,1}:
  -2
 -18
 -12

and of course the other order gives the same result

In [26]:
[1,9,6] * -2

3-element Array{Int64,1}:
  -2
 -18
 -12

## inner product

$a^T b$ is written as

In [27]:
a=[1,2,3]; b=[4,5,6];
dot(a, b)

32

## Norm and distance

The norm $\lVert x \rVert = \sqrt{x_1^2 + x_2^2 + \dots \ x_n^2}$ is written

In [28]:
norm(a)

3.7416573867739413

The distance $\lVert x - y \rVert$ is written

In [29]:
norm(a - b)

5.196152422706632

## RMS value

RMS is defined as

$$
\textbf{rms}(x) = \sqrt{\frac{1}{n} \left( x_1^2 + \dots + x_n^2 \right)}
$$

and can be expressed as

In [30]:
rms_x = norm(x) / sqrt(length(x))

9.389027966400258

## Standard deviation

Standard deviation is defined as

$$
\textbf{std}(x) = \frac{\lVert x - \bar{x} \textbf{1} \rVert}{\sqrt n}
$$

In [31]:
std_of_x = norm(x - mean(x)) / sqrt(length(x))

6.662622047240762

## Angle between vectors

The angle between vectors $a$ and $b$ is

$$
\angle (a,b) = \arccos \left( \frac{a^T b}{\lVert a \rVert \lVert b \rVert} \right)
$$

In [32]:
angle_a_b = acos(dot(a,b) / (norm(a) * norm(b)))

0.2257261285527342