Matrices in Julia are represented by 2D arrays

In [1]:
A = [2 -4 8.2 ; -5.5 3.5 63]

2×3 Array{Float64,2}:
  2.0  -4.0   8.2
 -5.5   3.5  63.0

Spaces separate entries in a row, semicolons separate individual rows

In [2]:
size(A)

(2,3)

In [3]:
n, m = size(A);
n

2

row vectors are $1 \times n$ matrices, e.g. `[4 8.7 -9]`

## Indexing and slicing

$A_{ij}$ is found with

In [4]:
A[1,2]

-4.0

can use ranges: the submatrix $A_{1:2,1:3}$ is

In [5]:
A[1:2,1:3]

2×3 Array{Float64,2}:
  2.0  -4.0   8.2
 -5.5   3.5  63.0

`A[:]` stacks the columns of A as a vector (column-major order)

In [6]:
A[:]

6-element Array{Float64,1}:
  2.0
 -5.5
 -4.0
  3.5
  8.2
 63.0

while `A'[:]` stacks the rows of A as a vector (row-major order)

In [7]:
A'[:]

6-element Array{Float64,1}:
  2.0
 -4.0
  8.2
 -5.5
  3.5
 63.0

## Block matrices

A block matrix

$$
X = \left[ \begin{array}{cc}
A & B \\
C & D \\
\end{array} \right]
$$

is formed with

In [8]:
B = [4;4]
C = ones(size(A))
D = ones(size(B))

2-element Array{Float64,1}:
 1.0
 1.0

In [9]:
[A B ; C D]

4×4 Array{Float64,2}:
  2.0  -4.0   8.2  4.0
 -5.5   3.5  63.0  4.0
  1.0   1.0   1.0  1.0
  1.0   1.0   1.0  1.0

usual rules governing dimensions apply

## Useful matrices in Julia

- $\textbf{0}_{m\times n}$ is `zeros(m,n)`
- $m \times n$ matrix with all entries 1 is `ones(m,n)`
- $I_{n \times n}$ is `eye(n)`
- $\textbf{diag}(x)$ is `diagm(x)` where $x$ is a vector

In [10]:
diagm([1,2,3])

3×3 Array{Int64,2}:
 1  0  0
 0  2  0
 0  0  3

## Transpose and matrix addition

$A^T$ is

In [11]:
A'

3×2 Array{Float64,2}:
  2.0  -5.5
 -4.0   3.5
  8.2  63.0

## Matrix-vector multiplication

In [12]:
[1 2; 3 4] * [5,6]

2-element Array{Int64,1}:
 17
 39

## Matrix multiplication

In [13]:
[2 4 3; 3 1 5] * [3 10; 4 2; 1 7]

2×2 Array{Int64,2}:
 25  49
 18  67

`A^k` is $A^k$ (for square matrix $A$)

In [14]:
E = [1 2; 3 4]

2×2 Array{Int64,2}:
 1  2
 3  4

In [15]:
E^2

2×2 Array{Int64,2}:
  7  10
 15  22

## Other functions

In [16]:
sum(E)

10

In [17]:
mean(A)

11.200000000000001

In [18]:
max(E, E^2)

2×2 Array{Int64,2}:
  7  10
 15  22

In [19]:
max(E, 3)

2×2 Array{Int64,2}:
 3  3
 3  4

`norm(A)` is not what you might think

In [20]:
norm(E)

5.464985704219043

in order to find $(\sum_{i,j} A_{ij}^2)^{1/2}$, use `norm(A[:])` or `vecnorm(A)`

In [21]:
norm(E[:])

5.477225575051661

In [22]:
A

2×3 Array{Float64,2}:
  2.0  -4.0   8.2
 -5.5   3.5  63.0

In [23]:
norm(A)

63.81337228347805

In [24]:
vecnorm(A)

64.02140267129423

## Computing regression model RMS error

the math:

- $X$ is an $n \times N$ matrix whose $N$ columns are feature $n$-vectors
- $y$ is the $N$-vector of associated outcomes
- regression model is $\hat y = X^T \beta + v$ where $\beta$ is $n$-vector, $v$ is scalar
- RMS error is $\textbf{rms}(\hat y - y)$

In Julia:

    y_hat = X'*beta + v
    rms_error = norm(y_hat - y) / sqrt(length(y))
